### ISSUE TITLE
Is there an API call that clears the cache?

### ISSUE THREAD

**Issue by jaswsinc** [websharks/zencache-kb#10]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

---
**Markdown File:** https://github.com/websharks/zencache-kb/blob/master/questions/10-api-call-that-clears-cache.md
**Published Link:** http://zencache.com/kb-article/is-there-an-api-call-that-clears-the-cache/

**Comment by raamdev** [comment]
Updated article draft to add a link to http://codex.wordpress.org/Must_Use_Plugins.

**Comment by jaswsinc** [comment]
Updated to full Issue URL to remain consistent with Raam's work thus far.

**Comment by jaswsinc** [comment]
Updating the `exit;` call to `exit('cache cleared')`.
