### ISSUE TITLE
How do I disable Static CDN Filters via PHP?

### ISSUE THREAD

**Issue by raamdev** [websharks/zencache-kb#100]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

---

### KB Article Published @ zencache.com<br />:page_with_curl: See: [How do I disable Static CDN Filters via PHP?](http://zencache.com/kb-article/how-do-i-disable-static-cdn-filters-via-php/)
[:octocat: View Markdown File](https://github.com/websharks/zencache-kb/blob/master/questions/2015/100-how-do-i-disable-static-cdn-filters-via-php.md) | [:pencil2: Edit Markdown File](https://github.com/websharks/zencache-kb/edit/master/questions/2015/100-how-do-i-disable-static-cdn-filters-via-php.md)

---

**Comment by jaswsinc** [comment]
@raamdev Note that I left the `$` out of `options` in the argument list above.

**Comment by jaswsinc** [comment]
Sorry about that. I goofed. It should have been `$options`.

**Comment by raamdev** [comment]
@jaswsinc Ah, thanks for catching that! :-) Fixed.

**Comment by d--j** [comment]
`<?php` twice won't work. Remove the second one or add a closing `?>` before it.

**Comment by jaswsinc** [comment]
@d--j Thanks for the heads up. Fixed :-)

**Comment by BookClubs** [comment]
I'd like to recommend an amendment to the following page:

https://cometcache.com/kb-article/how-do-i-disable-static-cdn-filters-via-php/

I needed to remove CDN on a directory, so I used the following:

`<?php
/*
Plugin Name: Disable Comet Cache Static CDN Filters via PHP
Description: Disables Comet Cache Static CDN Filters via PHP
Author: WebSharks, Inc.
Version: 1.0
Author URI: http://www.websharks-inc.com
*/

add_filter('comet_cache_options', function($options) {

$url = $_SERVER["REQUEST_URI"];
$uri_contains = strpos($url, 'directory');

    if($uri_contains!==false) {
        $options['cdn_enable'] = '0';
    }
    return $options;
});`

I'm not a programmer.  This was cobbled together from reading a few stackoverflow threads.  It appears to work. Could you please let me know if this is correct?  I figure some others might benefit from it too.

Thanks,
Chris

**Comment by raamdev** [comment]
@BookClubs Yes, that would work, however there is room there for unexpected behavior here. For example, if you had a URL that contained the `directory` fragment, you might unexpectedly disable Static CDN Filters for that page. For example, what if we had a Post URI like the following: `/hello-world-directory/`. In that case, the Static CDN Filters would be disabled for that page because its URI contained `directory`. You could further minimize the chances of this occurring in your code by including the directory separators (forward slashes): `/directory/`.
