### ISSUE TITLE
Google AdSense

### ISSUE THREAD

**Issue by WideStance** [websharks/zencache-kb#103]
Hi ZenCache,

My understanding is limited, so please bear with me.

The lite version is installed on my blog.

When Google ad code is removed, the advert still loads, until the cache is cleared. 

Is there an option in settings that will remove the advert without the need to clear the cache?

Thanks,
WideStance

**Comment by raamdev** [comment]
@WideStance We reserve this GitHub repo for drafting and publishing KB Articles. Please post support questions to the [WordPress.org Support Forum](https://wordpress.org/support/plugin/zencache) (for ZenCache Lite) or open a [Trouble Ticket](https://www.websharks-inc.com/support/?product=zencache&request_type=trouble_ticket) (ZenCache Pro). Thank you! :)
