### ISSUE TITLE
ZenCache Pro Migration FAQ

### ISSUE THREAD

**Issue by raamdev** [websharks/zencache-kb#107]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

---

Published article: https://cometcache.com/kb-article/how-to-migrate-from-zencache-pro-to-comet-cache-pro/
Markdown file: https://github.com/websharks/comet-cache-kb/blob/master/tutorials/107-migrating-zencache-pro-to-comet-cache-pro.md

**Comment by karenratte** [comment]
Will ZenCache be deleted after install or shall I delete it manually?

**Comment by raamdev** [comment]
@karenratte Yes, you can delete it. See [Can I delete ZenCache Pro before installing Comet Cache Pro?](https://cometcache.com/kb-article/how-to-migrate-from-zencache-pro-to-comet-cache-pro/#toc-f383a048)

**Comment by raamdev** [comment]
@karenratte I've updated the article to clarify the question, ["Can I delete ZenCache Pro?"](https://cometcache.com/kb-article/how-to-migrate-from-zencache-pro-to-comet-cache-pro/#toc-d031cf32)

Thanks for the feedback! :smile:

**Comment by karenratte** [comment]
Actually, 
I found that I HAD to delete ZEN CACHE before it would read CometCache properly and change the verbiage in the VIEW SOURCE to COMETCACHE and actually begin to cache. 
I deleted ZenCache plugin and everything works properly now. 
so please ignore my support request. 
thanks

**Comment by raamdev** [comment]
@karenratte Thank you for the feedback. I have improved the KB Article. :-)

**Comment by kristineds** [comment]
@raamdev The blog post link is redirecting to a 404 page. Shouldn't it be this one instead? [Announcing Comet Cache™ (formerly ZenCache)
](https://cometcache.com/blog/announcing-comet-cache-formerly-zencache/)

![screen shot 2017-01-30 at 11 40 13 pm](https://cloud.githubusercontent.com/assets/7514953/22429440/9281158a-e745-11e6-9940-804c42fd0a54.png)

**Comment by raamdev** [comment]
@kristineds Fixed! Thank you. 😄
