### ISSUE TITLE
Visual Composer Post Grid

### ISSUE THREAD

**Issue by ThePopularizer** [websharks/zencache-kb#109]
I'm experiencing a conflict with Visual Composer's Post Grid at the moment, where, after a few days of having it cached, it would not load; more precisely, it shows the loading graphics, but it would not load the actual posts. Strangely enough, it works fine soon after the cache is cleared or when it is first cached. It's a little difficult to troubleshoot, given this element of time interval. The issue remains even when the exception is made for js_composer in the HTML compressor. 

I've also [submitted this issue](http://codecanyon.net/item/visual-composer-page-builder-for-wordpress/242431/comments?page=570&filter=all#comment_12412087) to them on the VC CodeCanyon site. 

Thanks for you time!

**Comment by raamdev** [comment]
@ThePopularizer This GitHub repo is for KB articles. There's already a GitHub issue for improving ZenCache compatibility with Visual Composer Post Grid here: https://github.com/websharks/zencache/issues/673

I suggest posting your notes on that GitHub issue.
