### ISSUE TITLE
How can I move CSS/JS scripts into the footer?

### ISSUE THREAD

**Issue by jaswsinc** [websharks/zencache-kb#11]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

---

[:octocat: View Markdown File](https://github.com/websharks/zencache-kb/blob/master/questions/2015/11-how-can-i-move-cssjs-scripts-into-the-footer.md) | [:pencil2: Edit Markdown File](https://github.com/websharks/zencache-kb/edit/master/questions/2015/11-how-can-i-move-cssjs-scripts-into-the-footer.md)
:page_with_curl: **Published KB Article:** http://zencache.com/kb-article/how-can-i-move-cssjs-scripts-into-the-footer/

---

**Comment by raamdev** [comment]
Awesome article! I added the missing `questions` label.

**Comment by jaswsinc** [comment]
> I added the missing questions label.

Ah. Thanks! I forgot that was needed.

**Comment by raamdev** [comment]
Published! http://zencache.com/kb-article/how-can-i-move-cssjs-scripts-into-the-footer/

**Comment by pkiula** [comment]
It'll be nice to have a sample of where and how the wp_enqueue thing can be put. In functions.php file?

**Comment by raamdev** [comment]
@pkiula Please see the WordPress Developer Documentation: https://developer.wordpress.org/reference/functions/wp_enqueue_script/

**Comment by pkiula** [comment]
Thank you raamdev. Naturally I saw that, but it didn't completely do away with my doubts. Let's say I have the following scripts in the footer and I'd like Comet Cache to compress and minify them just before the closing body tag. Where should I put the `wp_enqueue..` function. In my functions.php file? Thank you. 

    
        <script src="js/vendor/jquery.js"></script>
        <script src="js/vendor/jquery.transit.min.js"></script>
        <script src="js/vendor/what-input.js"></script>
        <script src="js/vendor/foundation.js"></script>
        <script src="app.js"></script>
    
    
    </body>
    </html>

**Comment by raamdev** [comment]
@pkiula Yes, `functions.php` would work. But if you've got a plugin or theme already enqueuing those scripts, you'll need to modify them to enqueue the scripts in the footer (the `wp_enqueue_script()` function accepts a `$in_footer` parameter that lets you define that the script should be loaded in the footer... you're not supposed to place the `wp_enqueue_script()` function in a special place to have it load the script in the footer...). 

If you need help with WordPress functions and their usage, I recommend posting on the [WordPress Support Forum](https://wordpress.org/support/forum/wp-advanced/). We reserve GitHub for filing bug reports and making feature requests.
