### ISSUE TITLE
Migrating from Quick Cache (Lite) to ZenCache (Lite)

### ISSUE THREAD

**Issue by raamdev** [websharks/zencache-kb#12]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

- [x] Add screenshot(s) showing the migration activation message
- [x] Include a section about getting help if you run into issues with the migration process
- [ ] Do a short migration video tutorial that goes through the same process outlined here

---

**Markdown File:** https://github.com/websharks/zencache-kb/blob/master/tutorials/12-migrating-quick-cache-to-zen-cache.md
**Published Link:** http://zencache.com/kb-article/how-to-migrate-from-quick-cache-lite-to-zencache-lite/

**Comment by raamdev** [comment]
_Forked from websharks/zencache.com#14._

Working on this now. I'm writing this as a KB Article Tutorial. I'm going to start by answering these questions, but if you have ideas for any others, I'd love to hear them!

> - How do I install ZenCache Pro if I already have Quick Cache Pro installed?
> - Will my old Quick Cache Pro settings carry over?
> - I already purchased Quick Cache Pro; do I need to purchase ZenCache Pro?

---

I'm going to create two KB Article Tutorials: 

- Migrating from Quick Cache (Lite) to ZenCache (Lite)
- Migrating from Quick Cache Pro to ZenCache Pro

Having separate articles will make it easier to link to the specific article for the appropriate audience (for example, inside a Dashboard notice).

**Comment by raamdev** [comment]
It would be nice to do a short migration video tutorial that goes through the same procedure outlined here for migrating from Quick Cache to ZenCache.

**Comment by raamdev** [comment]
> Do a short migration video tutorial that goes through the same process outlined here

I'm holding off on doing a video until we have ZenCache published to WordPress.org, that way we can do a video that actually shows the install from the plugin repository.

**Comment by jaswsinc** [comment]
> I'm holding off on doing a video until we have ZenCache published to WordPress.org, that way we can do a video that actually shows the install from the plugin repository.

Copy that.

**Comment by raamdev** [comment]
Working on creating the Markdown file for this and publishing it on ZenCache.com.

**Comment by raamdev** [comment]
Published! http://zencache.com/kb-article/how-to-migrate-from-quick-cache-lite-to-zencache-lite/

**Comment by johnh10** [comment]
Under step-by-step migration:
"When installing the ZenCache plugin, ZenCache will automatically detect and preserve your existing Quick Cache settings. Once ZenCache has been activated, Quick Cache will be deactivated. All of this happens automatically; all you need to do is install the ZenCache plugin."

Then below in FAQ:
I already have Quick Cache installed; how do I install ZenCache?
You will need to disable Quick Cache and then install ZenCache. 

So which is correct?

**Comment by jaswsinc** [comment]
Hi John! :-)

I can see where that might be a little confusing. Thanks for the feedback.

The answer is that both ways are OK. The update will work as expected (i.e., ZenCache will pick up your Quick Cache options) no matter if Quick Cache is enabled at the time of the update, or not. So either way is OK :-)

The only thing that's NOT OK, is if you completely uninstall Quick Cache (with Plugin Deletion Safeguards off in Quick Cache). In other words, if you completely uninstall Quick Cache (and effectively erase all data for that plugin) before the update, ZenCache will have no ability to pull in your prior Quick Cache options.
