### ISSUE TITLE
Migrating from Quick Cache Pro to ZenCache Pro

### ISSUE THREAD

**Issue by raamdev** [websharks/zencache-kb#13]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

- [x] Include a section about getting help if you run into issues with the migration process

---

**Markdown File:** https://github.com/websharks/zencache-kb/blob/master/tutorials/13-migrating-quick-cache-pro-to-zencache-pro.md
**Published Link:** http://zencache.com/kb-article/migrating-from-quick-cache-pro-to-zencache-pro/

**Comment by raamdev** [comment]
_Forked from websharks/zencache.com#14._

Working on this now. I'm writing this as a KB Article Tutorial. I'm going to start by answering these questions, but if you have ideas for any others, I'd love to hear them!

> - How do I install ZenCache Pro if I already have Quick Cache Pro installed?
> - Will my old Quick Cache Pro settings carry over?
> - I already purchased Quick Cache Pro; do I need to purchase ZenCache Pro?

---

I'm going to create two KB Article Tutorials: 

- Migrating from Quick Cache (Lite) to ZenCache (Lite)
- Migrating from Quick Cache Pro to ZenCache Pro

Having separate articles will make it easier to link to the specific article for the appropriate audience (for example, inside a Dashboard notice).

**Comment by raamdev** [comment]
It would be nice to do a short migration video tutorial that goes through the same procedure outlined here for migrating from Quick Cache to ZenCache. (I plan to do one for #12.)

**Comment by raamdev** [comment]
Additional questions for the FAQ:

- How many years of Support & Upgrades will I receive if I'm already a Quick Cache Pro customer? [_I suggest 3 years, the same as if they were purchasing a new license._]
- What if I don't remember my account details for Quick Cache Pro?

**Comment by jaswsinc** [comment]
@raamdev This article is ready for another review.
Video is here: https://www.youtube.com/watch?v=AXVJK_oyJg8

**Comment by raamdev** [comment]
@jaswsinc Awesome article! I just reviewed this and it looks 100% ready to go. :-) 

I did add a sentence to _How do I install ZenCache if I already have Quick Cache installed?_ to avoid the chances of somebody reading that section, then immediately deactivating _and_ deleting Quick Cache prior to installing ZenCache; we want to make sure they don't delete Quick Cache until ZenCache has copied over the settings.

**Comment by jaswsinc** [comment]
> we want to make sure they don't delete Quick Cache until ZenCache has copied over the settings.

Copy that. Great!

**Comment by raamdev** [comment]
Working on creating the Markdown file for this and publishing it on ZenCache.com.

**Comment by raamdev** [comment]
Published! http://zencache.com/kb-article/migrating-from-quick-cache-pro-to-zencache-pro/
