### ISSUE TITLE
How do I setup Static CDN Filters w/ Amazon CloudFront?

### ISSUE THREAD

**Issue by raamdev** [websharks/zencache-kb#19]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

- [ ] Update link in footer to _Introduction to Static CDN Filters_ to use published KB article link 

---
**Markdown File:** https://github.com/websharks/zencache-kb/blob/master/questions/19-how-to-setup-static-cdn-filters-amazon-cloudfront.md

**Published Link:** http://zencache.com/kb-article/how-do-i-setup-static-cdn-filters-w-amazon-cloudfront/

**Comment by BookClubs** [comment]
I watched the video on setting up Amazon CloudFront.  Does anything need to be done at my domain registrar?  Do I need to change the DNS settings?  There's no mention of that in the video.

**Comment by raamdev** [comment]
@BookClubs Thanks for the question. I updated the KB Article to answer your question here: https://cometcache.com/kb-article/how-do-i-setup-static-cdn-filters-w-amazon-cloudfront/#toc-84be12da
