### ISSUE TITLE
Introduction to Static CDN Filters

### ISSUE THREAD

**Issue by raamdev** [websharks/zencache-kb#20]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

---

**Markdown File:** https://github.com/websharks/zencache-kb/blob/master/tutorials/20-introduction-static-cdn-filters.md

**Published Link:** http://zencache.com/kb-article/introduction-to-static-cdn-filters/

**Comment by jaswsinc** [comment]
Excellent article! Nice work Raam :+1:

**Comment by raamdev** [comment]
@jaswsinc: I tried to update this KB Article on GitHub (the markdown file; see commit https://github.com/websharks/zencache-kb/commit/365d30b53dd957d784632009515ac89595b6a6b3) after it was imported to ZenCache.com via WP KB Articles, but rerunning the ZenCache.com WP KB Articles GitHub Processor did not update the Post on ZenCache.com: 

https://zencache.com/wp-admin/post.php?post=852&action=edit 

Can you take a look at this for me and leave your update here?

**Comment by jaswsinc** [comment]
I tried to reproduce this last night before some of the other changes and reprocessing took place at ZenCache.com. I might have missed something, but I was unable to reproduce it. I did notice that there seems to be a left-hanging `[` in this article, and I'm wondering if that could have thrown you off?

https://zencache.com/?post_type=kb_article&p=880&preview=true

![2015-02-14_14-29-40](https://cloud.githubusercontent.com/assets/1563559/6201441/0575fb0c-b456-11e4-8665-54647f013b80.png)

In either case, I'll keep an eye on this in case it happens again.

**Comment by raamdev** [comment]
> I might have missed something, but I was unable to reproduce it. I did notice that there seems to be a left-hanging [ in this article, and I'm wondering if that could have thrown you off?

I was trying to fix something related to that left-hanging bracket (https://github.com/websharks/zencache-kb/commit/365d30b53dd957d784632009515ac89595b6a6b3) but the changes from that commit never got pushed over to ZenCache.com, even after running the WP KB Articles GitHub Processor manually.

In any case, I just fixed the left-hanging bracket (https://github.com/websharks/zencache-kb/commit/0048967cc22a13a2f70a77616a0dd21fbb749a26) and manually ran the WP KB Articles GitHub Processor again and this time the change was copied over to ZenCache.com as expected.

Must've just been a glitch. :-)

**Comment by jaswsinc** [comment]
Copy that. Something to keep an eye on. Thanks.

**Comment by QloudPress** [comment]
In your article you say its more difficult to integrate ZenCache with CloudFlare but you don't explain how, why, or what are the workarounds. I have a PRO CloudFlare account and simply buying another CDN, while an option, is far from ideal. Couldn't you push the boat out just a little way further?

**Comment by karen1633** [comment]
Following up from QloudPress comment above - instructions on how to integrate with CloudFlare or a workaround would be very useful please

**Comment by raamdev** [comment]
@QloudPress @karen1633 I've started a new KB Article draft that will address your questions: https://github.com/websharks/zencache-kb/issues/50

Please click the "Subscribe" button on that GitHub Issue to follow along.

**Comment by deadparrotsoftware** [comment]
while we have CloudFlare, we also have Amazon S3 - you do not cover IF that can be used, and how. (which is odd, as you DO discuss S3 in s2member)

**Comment by raamdev** [comment]
@deadparrotsoftware Amazon S3 is a file storage service, designed to serve file downloads. It is not designed specifically as a Content Distribution Network (CDN). Amazon's CDN service is called **CloudFront** (which is actually built on top of Amazon S3). ZenCache Static CDN Filters _do_ integrate with Amazon CloudFront; see [How do I setup Static CDN Filters w/ Amazon CloudFront?](http://zencache.com/kb-article/how-do-i-setup-static-cdn-filters-w-amazon-cloudfront/).

Thank you for the question. :-) I'll add a section to the bottom of the article that explains this better.
