### ISSUE TITLE
Introduction to Dynamic Version Salts

### ISSUE THREAD

**Issue by raamdev** [websharks/zencache-kb#21]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

- [x] Update [ZenCache.com Redirect](https://zencache.com/wp-admin/post.php?post=840&action=edit) to point to published KB Article on Live site.

---
**Markdown File:** https://github.com/websharks/zencache-kb/blob/master/tutorials/21-introduction-dynamic-version-salts.md

**Published Link:** http://zencache.com/kb-article/introduction-to-dynamic-version-salts/

**Comment by ioerjfoige0439i** [comment]
In this instance you should probably use strpos (or mb_strpos if UTF-8) since it's faster than preg_match. So change:

preg_match('/iPhone/i', $_SERVER['HTTP_USER_AGENT']) ? 'iPhones' : ''

to 

(strpos($_SERVER['HTTP_USER_AGENT'],'/iPhone/i') > -1) ? 'iPhones' : ''

or

(strpos($_SERVER['HTTP_USER_AGENT'],'/iPhone/i') !== FALSE) ? 'iPhones' : ''

**Comment by kristineds** [comment]
@raamdev I noticed that the links for the **example plugin file** are all pointing to a 404 error page. :) Should it be redirecting to this? https://github.com/websharks/comet-cache-pro/blob/000000-dev/src/includes/templates/ac-plugin.txt

![screen shot 2016-04-05 at 12 35 19 am](https://cloud.githubusercontent.com/assets/7514953/14255461/aee4bdc4-fac6-11e5-91e2-489b7f8f75a3.png)

**Comment by raamdev** [comment]
@kristineds Yes, thank you for catching that! I've updated the link.
