### ISSUE TITLE
Disabling Automatic Clear / Wipe Cache Routines

### ISSUE THREAD

**Issue by raamdev** [websharks/zencache-kb#25]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

---
**Markdown File:** https://github.com/websharks/zencache-kb/blob/master/tutorials/25-disabling-automatic-clear-wipe-cache-routines.md

**Published KB Article:** http://zencache.com/kb-article/disabling-automatic-clear-wipe-cache-routines/

**Comment by lkraav** [comment]
Guys, just use `add_filter( ..., '__return_true' );` instead of making separate callback functions.

**Comment by raamdev** [comment]
@lkraav Thanks! :-) That has been updated.
