### ISSUE TITLE
How do I disable cache locking?

### ISSUE THREAD

**Issue by raamdev** [websharks/zencache-kb#31]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

---

**Markdown file:** https://github.com/websharks/zencache-kb/blob/master/questions/31-disable-cache-locking.md

**Published file:** http://zencache.com/kb-article/how-do-i-disable-cache-locking/

**Comment by raamdev** [comment]
Waiting for resolution on https://github.com/websharks/wp-kb-articles/issues/81

**Comment by jaswsinc** [comment]
Cool. I did not realize we made this possible.

**Comment by raamdev** [comment]
> I did not realize we made this possible.

Haha, yeah, I had forgotten to until I decided to see if there was a way to do it and recalled doing something to make it possible. :-) Hence the value of KB Articles like these!

**Comment by jaswsinc** [comment]
I discovered while working on the restructure, that this article asks them to create an AC Plugin file. The filter call that we use for this, like the one for altering the lock type, uses `->apply_wp_filters()`. Meaning, it's not using an AC Plugin filter, it's using an ordinary WP plugin filter.

We should update this article so it's suggests an MU Plugin instead.

## As Of Right Now, Like This

`/wp-content/mu-plugins/zc-disable-cache-locking.php`

```php
<?php
add_filter('zencache\\share_disable_cache_locking', '__return_true');
```

## After Restructure Is Complete

`/wp-content/mu-plugins/zc-disable-cache-locking.php`

- The preferred filter name will be: `zencache_disable_cache_locking`  
  _The old name will continue to work however._

```php
<?php
add_filter('zencache_disable_cache_locking', '__return_true');
```

**Comment by raamdev** [comment]
@jaswsinc I recall you telling me that ZenCache likely won't function properly with cache locking disabled, that too many areas of the codebase _expect_ there to be a lock on the cache. Is this still true/ If so, I'd say we should scrap this KB article.

**Comment by jaswsinc** [comment]
So sorry for the delayed response. Yes, that is still true. ~ Closing this.

**Comment by raamdev** [comment]
Closing... but shouldn't we first remove the published KB article so that people don't find it and try disabling cache locking? http://zencache.com/kb-article/how-do-i-disable-cache-locking/

**Comment by jaswsinc** [comment]
> but shouldn't we first remove the published KB article so that people don't find it and try disabling cache locking? http://zencache.com/kb-article/how-do-i-disable-cache-locking/

Agree. Would you like me to do that?

**Comment by raamdev** [comment]
> Would you like me to do that?

I took care of it. Thanks!
