### ISSUE TITLE
What is Cache Locking?

### ISSUE THREAD

**Issue by jaswsinc** [websharks/zencache-kb#36]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

- [x] Need to clean this up; remove a section or two and reword for public consumption.

---

**Markdown File:** http://wsharks.com/1EHw6qC
**Published KB Article:** http://zencache.com/kb-article/what-is-cache-locking/

---

**Comment by jaswsinc** [comment]
@raamdev This article is ready for a review.

**Comment by raamdev** [comment]
@jaswsinc Reviewed. Only one small grammar correction (`it's` should've been `its` in the Semaphores paragraph). Wow, fantastic article! We need more stuff like this to really help people understand concepts that are not well-understood by many site owners (and even developers! this article was informative for me too).

I'd say this is ready to be published.

**Comment by jaswsinc** [comment]
Copy that. Thank you! :-)
