### ISSUE TITLE
How do Static CDN Filters work?

### ISSUE THREAD

**Issue by jaswsinc** [websharks/zencache-kb#39]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

---

[:octocat: View Markdown File](https://github.com/websharks/zencache-kb/blob/master/questions/2015/39-how-do-static-cdn-filters-work.md) | [:pencil2: Edit Markdown File](https://github.com/websharks/zencache-kb/edit/master/questions/2015/39-how-do-static-cdn-filters-work.md)
:page_with_curl: **Published KB Article:** http://zencache.com/kb-article/how-do-static-cdn-filters-work/

---

**Comment by jaswsinc** [comment]
Referencing internal ticket: https://websharks.zendesk.com/agent/tickets/5417

**Comment by raamdev** [comment]
Awesome article! I wonder if I can come up with a diagram for this.

**Comment by jaswsinc** [comment]
@raamdev writes...
> I wonder if I can come up with a diagram for this.

Oh yes, that'd be great.

---

I cleaned this article up just a bit and fixed some typos.

**Comment by raamdev** [comment]
Diagrams that can be added to this article:

![zencache-static-cdn-filters-enable-disable](https://cloud.githubusercontent.com/assets/53005/6723895/46153582-cdc5-11e4-9b17-b82bdf399a6f.png)
![zencache-static-cdn-filters-diagram](https://cloud.githubusercontent.com/assets/53005/6723898/47a2d062-cdc5-11e4-8933-ed0133a9fc08.png)

**Comment by jaswsinc** [comment]
Awesome diagrams :-) Woohoo!

---

I removed `aka: Source` from this article to avoid confusion.

**Comment by raamdev** [comment]
@jaswsinc I made some edits, added an intro, and published. Thanks so much! http://zencache.com/kb-article/how-do-static-cdn-filters-work/

**Comment by jaswsinc** [comment]
Awesome!
