### ISSUE TITLE
What is the recommended Nginx Configuration?

### ISSUE THREAD

**Issue by raamdev** [websharks/zencache-kb#4]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

---

**Markdown File:** https://github.com/websharks/zencache-kb/blob/master/questions/4-recommended-nginx-config.md

**Comment by raamdev** [comment]
@jaswsinc Anything else we might want to add here?

**Comment by jaswsinc** [comment]
Looks good to me. I can't think of anything else to add.

**Comment by raamdev** [comment]
> Looks good to me.

Copy. Thanks!
