### ISSUE TITLE
Does ZenCache clear the CDN cache?

### ISSUE THREAD

**Issue by jaswsinc** [websharks/zencache-kb#40]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

---

[:octocat: View Markdown File](https://github.com/websharks/zencache-kb/blob/master/questions/2015/40-does-zencache-clear-the-cdn-cache.md) | [:pencil2: Edit Markdown File](https://github.com/websharks/zencache-kb/edit/master/questions/2015/40-does-zencache-clear-the-cdn-cache.md)
:page_with_curl: **Published KB Article:** http://zencache.com/kb-article/does-zencache-clear-the-cdn-cache/

---

**Comment by raamdev** [comment]
Where does the ZenCache use of `?iv=1` come into play here? When the cache is cleared manually, does that increment the `iv` query variable, thereby invalidating the existing cached files on the CDN and resulting in the CDN fetching a fresh copy?

The docs say:

>  ZenCache will automatically bump an internal counter each time you upgrade a WordPress component (e.g. a plugin, theme, or WP itself). **Or, if you ask ZenCache to invalidate the CDN cache (e.g. a manual clearing of the CDN cache); the internal counter is bumped then too.** In short, ZenCache handles cache invalidations for you reliably.

That would seem to imply that while clicking "Clear Cache" in ZenCache will not technically "clear the cached data" from the CDN, it will result in the existing cached data no longer being used, i.e., invalidated.

**Comment by jaswsinc** [comment]
@raamdev writes...
> Or, if you ask ZenCache to invalidate the CDN cache (e.g. a manual clearing of the CDN cache); the internal counter is bumped then too.

This is incorrect. I wrote this with the expectation that we would create a "Clear CDN Cache" button of some sort, but this never happened.

The only time the CDN Cache is cleared (i.e., the `?iv` being bumped) is when:

- WordPress is updated.
- A WP theme is updated.
- A WP plugin is updated.
- Your CDN expires the file and fetches a new copy. Most CDNs will be configured to do this based on the `Expires:` header that your server sends. So for instance, if your server sends an `Expires:` header for JS/CSS/images, that's long the CDN will cache it until it fetches it from your server again.

**Comment by raamdev** [comment]
> This is incorrect. I wrote this with the expectation that we would create a "Clear CDN Cache" button of some sort, but this never happened.

OK, so we need to remove that part of the docs from the Static CDN Filters inline docs during the next update. 

> Your CDN expires the file and fetches a new copy. Most CDNs will be configured to do this based on the Expires: header that your server sends. So for instance, if your server sends an Expires: header for JS/CSS/images, that's long the CDN will cache it until it fetches it from your server again.

Could you explain that part a bit more? How does ZenCache know that the CDN has expired the file and should therefore increment the `iv` counter? Or was that miscommunicated and you simply meant that as one of the scenarios in which the CDN cache of a file is cleared? i.e., that's not actually a scenario where `iv` is incremented; only the latter three scenarios result in ZenCache bumping the `iv` counter.

**Comment by jaswsinc** [comment]
@raamdev writes...
> Or was that miscommunicated and you simply meant that as one of the scenarios in which the CDN cache of a file is cleared?

Oh yes, sorry. I just meant that the CDN will automatically refresh a particular file whenever it reaches a max age which is based on the original headers that your server sent for the file. There is a more information on this here: http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Expiration.html

**Comment by raamdev** [comment]
Shortened the title to **Does ZenCache clear the CDN cache?**

**Comment by raamdev** [comment]
Published! http://zencache.com/kb-article/does-zencache-clear-the-cdn-cache/
