### ISSUE TITLE
How do I setup Static CDN Filters with CDN77?

### ISSUE THREAD

**Issue by raamdev** [websharks/zencache-kb#46]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

---

**Markdown File:** http://wsharks.com/1AL6Edk
**Published KB Article:** http://zencache.com/kb-article/how-do-i-setup-static-cdn-filters-with-cdn77/

---

**Comment by jaswsinc** [comment]
> That's it! ZenCache Pro is now configured with your CDN77 account. If you logout of your WordPress Dashboard and visit your site, you'll see that all static resources (CSS files, JavaScript files, images, etc.) are loaded with URLs that start with something like http://579346857.r.cdn77.net/, which indicates that the ZenCache Pro CDN Integration is now working.

---

WOOHOO! Nice work on this @raamdev :+1:
