### ISSUE TITLE
How can I tell if ZenCache is working?

### ISSUE THREAD

**Issue by raamdev** [websharks/zencache-kb#48]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

---

[:octocat: View Markdown File](https://github.com/websharks/zencache-kb/blob/master/questions/2015/48-how-do-i-know-if-zencache-is-working.md) | [:pencil2: Edit Markdown File](https://github.com/websharks/zencache-kb/edit/master/questions/2015/48-how-do-i-know-if-zencache-is-working.md)
:page_with_curl: **Published KB Article:** http://zencache.com/kb-article/how-do-i-know-if-zencache-is-working/

---

**Comment by renzms** [comment]
@raamdev 

On the bulleted list of the section: **ZenCache is enabled but not working!**

The line: "Check your .htaccess file for code that may have bene added by other caching plugins..."

I noticed "been" is spelled incorrectly. Please change, thanks!

**Comment by jaswsinc** [comment]
Fixed. Thanks!
