### ISSUE TITLE
Why doesn't ZenCache move CSS/JS into the footer?

### ISSUE THREAD

**Issue by raamdev** [websharks/zencache-kb#49]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

---

[:octocat: View Markdown File](https://github.com/websharks/zencache-kb/blob/master/questions/2015/49-why-doesnt-zencache-move-cssjs-into-the-footer.md) | [:pencil2: Edit Markdown File](https://github.com/websharks/zencache-kb/edit/master/questions/2015/49-why-doesnt-zencache-move-cssjs-into-the-footer.md)
:page_with_curl: **Published KB Article:** http://zencache.com/kb-article/why-doesnt-zencache-move-cssjs-into-the-footer/

---

**Comment by jaswsinc** [comment]
This is a great article @raamdev! Thanks for putting it together.

> In such a scenario, forcing the scripts to load in the footer would have an adverse side effect: the visitor might see one thing as the page is loading, then something else entirely after the page finishes loading and the script in the footer finally loads and makes changes to the page.

I wanted to demonstrate another reason ↓

---

## Inline JavaScript API Calls

Here we have `<script src="widget-api.js"></script>` in the `<head>`.

```html
<!DOCTYPE html>
<html>
<head>
	<title>Example</title>
	<script src="widget-api.js"></script>
</head>
<body>
		<div class="widget">
			<script>displayWidget();</script>
		</div>
	</body>
</html>
```

## Changing the Order (Unintended Consequences)

Here we move `<script src="widget-api.js"></script>` to the footer.

```html
<!DOCTYPE html>
<html>
<head>
	<title>Example</title>
</head>
<body>
		<div class="widget">
			<script>displayWidget();</script> <!-- JavaScript error: displayWidget is undefined. -->
		</div>
		<script src="widget-api.js"></script>
	</body>
</html>
```

The call to `displayWidget()` will fail because it expects `widget-api.js` to have already been loaded; i.e., it expects `displayWidget()` to exist already.

**Comment by raamdev** [comment]
> I wanted to demonstrate another reason ↓

Thanks so much! I've updated the KB Article to include that example. Nice and simple! :-)
