### ISSUE TITLE
How can I restrict ZenCache to the Primary Blog in a WP Multisite Environment?

### ISSUE THREAD

**Issue by raamdev** [websharks/zencache-kb#57]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

---

[:octocat: View Markdown File](https://github.com/websharks/zencache-kb/blob/master/questions/2015/57-how-can-i-restrict-zencache-to-the-primary-blog-in-a-wp-multisite-environment.md) | [:pencil2: Edit Markdown File](https://github.com/websharks/zencache-kb/edit/master/questions/2015/57-how-can-i-restrict-zencache-to-the-primary-blog-in-a-wp-multisite-environment.md)
:page_with_curl: **Published KB Article:** http://zencache.com/kb-article/how-can-i-restrict-zencache-to-the-primary-blog-in-a-wp-multisite-environment/

---

**Comment by kristineds** [comment]
It would be nice if we could add the `WP Multisite` tag to this KB article so it's easier to search when one is using the Filter by Tag option on the KB page. :)

**Comment by raamdev** [comment]
@kristineds Thanks! Done. :-)
