### ISSUE TITLE
Why do speed testing services report that I need to Minify HTML when HTML Compression is already enabled?

### ISSUE THREAD

**Issue by raamdev** [websharks/zencache-kb#66]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

---

[:octocat: View Markdown File](https://github.com/websharks/zencache-kb/blob/master/questions/2015/66-why-are-testing-services-reporting-that-i-need-to-minify-html-when-html-compression-is-enabled.md) | [:pencil2: Edit Markdown File](https://github.com/websharks/zencache-kb/edit/master/questions/2015/66-why-are-testing-services-reporting-that-i-need-to-minify-html-when-html-compression-is-enabled.md)
:page_with_curl: **Published KB Article:** http://zencache.com/kb-article/why-are-testing-services-reporting-that-i-need-to-minify-html-when-html-compression-is-enabled/

---

**Comment by kristineds** [comment]
It would be nice if we could update the screenshot for this KB article to say Comet Cache instead of ZenCache. Use the one below instead ⬇️ .

![screen shot 2016-12-08 at 11 29 19 pm](https://cloud.githubusercontent.com/assets/7514953/21015890/96f91e44-bd9e-11e6-8ae1-60bda7c8f7fe.png)
