### ISSUE TITLE
What information does ZenCache Pro report to WebSharks?

### ISSUE THREAD

**Issue by raamdev** [websharks/zencache-kb#82]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

---

### KB Article Published @ zencache.com<br />:page_with_curl: See: [What information does ZenCache Pro report to WebSharks?](http://zencache.com/kb-article/what-information-does-zencache-pro-report-to-websharks/)
[:octocat: View Markdown File](https://github.com/websharks/zencache-kb/blob/master/questions/2015/82-what-information-does-zencache-pro-report-to-websharks.md) | [:pencil2: Edit Markdown File](https://github.com/websharks/zencache-kb/edit/master/questions/2015/82-what-information-does-zencache-pro-report-to-websharks.md)

---

**Comment by jaswsinc** [comment]
This looks ready to publish.

**Comment by raamdev** [comment]
@jaswsinc Awesome! Thanks so much for tweaking this. Looks great to me now too. I'll publish this as soon as I have the next Pro release ready to go.

**Comment by jaswsinc** [comment]
I just reviewed this article again. I see that you have clearly stated that it's "ZenCache Pro" that collects this information. It might be a good idea to add one more FAQ to the list though...

## Does ZenCache Lite collect stats?

No. The lite version (i.e., the version of ZenCache available at WordPress.org) does not collect statistics like this. Stats are collected from ZenCache Pro customers only.

**Comment by raamdev** [comment]
> It might be a good idea to add one more FAQ to the list though...

Great idea! Adding now.

**Comment by raamdev** [comment]
@jaswsinc Done. Thanks!

**Comment by jaswsinc** [comment]
Cool. I love the way this article came together. Nice job on showing example data too!
