### ISSUE TITLE
Why does ZenCache show an APC Extension Warning?

### ISSUE THREAD

**Issue by raamdev** [websharks/zencache-kb#83]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

---

### KB Article Published @ zencache.com<br />:page_with_curl: See: [Why does ZenCache show an APC Extension Warning?](http://zencache.com/kb-article/why-does-zencache-show-an-apc-extension-warning/)
[:octocat: View Markdown File](https://github.com/websharks/zencache-kb/blob/master/questions/2015/83-why-does-zencache-show-an-apc-extension-warning.md) | [:pencil2: Edit Markdown File](https://github.com/websharks/zencache-kb/edit/master/questions/2015/83-why-does-zencache-show-an-apc-extension-warning.md)

---

**Comment by raamdev** [comment]
@jaswsinc writes... 
> We could also run some tests with this INI directive: 
> http://php.net/manual/en/apc.configuration.php#ini.apc.filters
> If a site owner wants to keep APC, and still run the latest release of ZenCache Pro, they should be able to exclude the ZenCache closures from the APC cache and keep running; assuming they don't have any other plugins that use closures or otherwise trigger bugs in the APC extension.

We'll need to do the necessary research and testing to see if that's a possible solution and then update this KB Article with that additional workaround.

**Comment by jaswsinc** [comment]
```ini
apc.filters = "-.+?/zencache(?:\-pro)?/.+?/closures/.+"
```

Heading added above to address this point.

**Comment by jaswsinc** [comment]
This looks ready to publish.

**Comment by raamdev** [comment]
I added a new section: **What is the APC Extension?**

> Heading added above to address this point.

Perfect! Thank you!
