### ISSUE TITLE
Testing ZenCache in a Clean WordPress Installation

### ISSUE THREAD

**Issue by patdumond** [websharks/zencache-kb#86]
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

---

### KB Article Published @ zencache.com<br />:page_with_curl: See: [Testing ZenCache in a Clean WordPress Installation](http://zencache.com/kb-article/testing-zencache-in-a-clean-wordpress-installation/)
[:octocat: View Markdown File](https://github.com/websharks/zencache-kb/blob/master/tutorials/2015/86-testing-zencache-in-a-clean-wordpress-installation.md) | [:pencil2: Edit Markdown File](https://github.com/websharks/zencache-kb/edit/master/tutorials/2015/86-testing-zencache-in-a-clean-wordpress-installation.md)

---

**Comment by jaswsinc** [comment]
Nice adaptation. That looks great!

**Comment by raamdev** [comment]
@patdumond Nice adaption! Here are a few requested edits:

- [ ] I noticed this version is missing some of the bold formatting from the s2Member version (e.g., "How can that be?" should be bold.
- [ ] "Must-Use Plugins" is missing a link (see s2Member version)
- [ ] "Your WordPress installation has different plugins, it's had a different history, and it's probably running with a different theme too." ZenCache is also a bit more affected by server-side configurations than s2Member, so I suggest adding another sentence that says, "ZenCache also writes cache files to the server and interacts with other server software quite frequently and your server-side configuration is likely unique and different from ours."
- [ ] "and with each and every theme **and server configuration** that exists for WordPress"
- [ ] "If you find that the bug still exists, please report it! **There may still be a special server-side configuration that is causing the issue, but those can usually be resolved by working with your web hosting company to resolve the issue.**"

**Comment by patdumond** [comment]
@raamdev:

>ZenCache also writes cache files to the server and interacts with other server software quite frequently and your server-side configuration is likely unique and different from ours."

I changed this to: "ZenCache also writes cache files to the server and interacts with other server software quite frequently and your server-side configuration is likely different from ours." *Unique* means one-of-a-kind. If their server-side configuration is *Unique* there is no *likely*, it **is** different from ours. It is, however, more likely to just be "different from ours" rather than *unique*.

I made all of the other changes you requested.

**Comment by patdumond** [comment]
@raamdev: Ready for another review. Thanks in advance.

**Comment by raamdev** [comment]
> Unique means one-of-a-kind. If their server-side configuration is Unique there is no likely, it is different from ours. It is, however, more likely to just be "different from ours" rather than unique.

Good point! Thanks for correcting that. :-)

---

This looks good to me now, so I'm marking this as **approved** and publishing it. :-) Thanks!
