### ISSUE TITLE
How can I build a salt for all mobile devices?

### ISSUE THREAD

**Issue by jaswsinc** [websharks/zencache-kb#88]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

---

### KB Article Published @ zencache.com<br />:page_with_curl: See: [How can I build a salt for all mobile devices?](http://zencache.com/kb-article/how-can-i-build-a-salt-for-all-mobile-devices/)
[:octocat: View Markdown File](https://github.com/websharks/zencache-kb/blob/master/questions/2015/88-how-can-i-build-a-salt-for-all-mobile-devices.md) | [:pencil2: Edit Markdown File](https://github.com/websharks/zencache-kb/edit/master/questions/2015/88-how-can-i-build-a-salt-for-all-mobile-devices.md)

---

**Comment by jaswsinc** [comment]
@raamdev Quick review when you get a moment.

**Comment by raamdev** [comment]
@jaswsinc Looks great! Would you mind adding a one or two sentence introduction to this article? Maybe something that gives an example scenario where someone might want to implement something like this?

**Comment by jaswsinc** [comment]
> Would you mind adding a one or two sentence introduction to this article?

@raamdev Done. Thank you. Ready for another review.

**Comment by raamdev** [comment]
@jaswsinc Thanks! A few more requested edits:

- [ ] Flip the position of the two paragraphs (use the 2nd one first). Start with the What and Why of building a salt for mobile devices and then follow up with reasons the following wouldn't be necessary (i.e., If your site is "Responsive").
- [ ] "Step 1: Mobile Device Detection" ← I suggest changing that to "Step 1: Generating the Salt for Mobile Device Detection"
- [ ] "This file should reside in the same directory as /wp-config.php" ← Add a bold "**Note:**" to the start here to bring attention to this important line.
- [ ] "Step 2: Include `zc-is-mobile.php`" ← I suggest changing that to "Step 2: Include `zc-is-mobile.php` in your `wp-config.php`"
- [ ] Under Step 3, I suggest adding a sentence or two that explains what's going on by adding `zc_is_mobile()` to the ZenCache options panel (i.e., _you're telling ZenCache to use the `zc_is_mobile()` function that was defined in `zc-is-mobile.php`_)

**Comment by jaswsinc** [comment]
@raamdev List items checked off. Ready for another review.

**Comment by raamdev** [comment]
@jaswsinc Woohoo! Excellent. This looks ready to me. :-)

**Comment by KeithPantlin** [comment]
Hello Jason,

I think your definitions of what is a mobile device are too broad. For example, you have defined ALL Android devices as mobiles, but surely tablets with Android OS should not be defined as mobiles.

The WPTouch plugin's wptouch/core/mobile-user-agents.php file, mobiles are selected by the following:

$settings = wptouch_get_settings();

if ( $settings->enable_ios_phone ) {
	$wptouch_smartphone_list[] = array( 'iPhone' ); // iPhone
	$wptouch_smartphone_list[] = array( 'iPod', 'Mobile' ); // iPod touch
}

if ( $settings->enable_android_phone ) {
	$wptouch_smartphone_list[] = array( 'Android', 'Mobile' ); // Android devices
}

if ( $settings->enable_blackberry_phone ) {
	$wptouch_smartphone_list[] = array( 'BB', 'Mobile Safari' ); // BB10 devices
	$wptouch_smartphone_list[] = array( 'BlackBerry', 'Mobile Safari' ); // BB 6, 7 devices
}

if ( $settings->enable_firefox_phone ) {
	$wptouch_smartphone_list[] = array( 'Firefox', 'Mobile' ); // Firefox OS devices
}

if ( $settings->enable_windows_phone ) {
	$wptouch_smartphone_list[] = array( 'IEMobile/11', 'Touch' ); // Windows IE 11 touch devices
	$wptouch_smartphone_list[] = array( 'IEMobile/10', 'Touch' ); // Windows IE 10 touch devices
	$wptouch_smartphone_list[] = 'IEMobile/9.0'; // Windows Phone OS 9
	$wptouch_smartphone_list[] = 'IEMobile/8.0'; // Windows Phone OS 8
	$wptouch_smartphone_list[] = 'IEMobile/7.0'; // Windows Phone OS 7
}

if ( $settings->enable_opera_phone ) {
	$wptouch_smartphone_list[] = array( 'OPiOS', 'Mobile' ); // Opera Mini iOS
	$wptouch_smartphone_list[] = array( 'Coast', 'Mobile' ); // Opera Coast iOS
}


Using these definitions, my   zc-is-mobile.php   is 

<?php
function zc_is_mobile() {
    static $salt = null;
    if ( isset( $salt ) ) {
        return $salt;
    }
    if ( empty($_SERVER['HTTP_USER_AGENT']) ) {
        $salt = '';
    } elseif ( strpos($_SERVER['HTTP_USER_AGENT'], 'iPhone') !== false
        || (strpos($_SERVER['HTTP_USER_AGENT'], 'iPod') !== false && strpos($_SERVER['HTTP_USER_AGENT'], 'Mobile') !== false)
        || (strpos($_SERVER['HTTP_USER_AGENT'], 'Android') !== false && strpos($_SERVER['HTTP_USER_AGENT'], 'Mobile') !== false)
        || (strpos($_SERVER['HTTP_USER_AGENT'], 'BB') !== false && strpos($_SERVER['HTTP_USER_AGENT'], 'Mobile Safari') !== false)
        || (strpos($_SERVER['HTTP_USER_AGENT'], 'BlackBerry') !== false && strpos($_SERVER['HTTP_USER_AGENT'], 'Mobile Safari') !== false)
        || (strpos($_SERVER['HTTP_USER_AGENT'], 'Firefox') !== false && strpos($_SERVER['HTTP_USER_AGENT'], 'Mobile') !== false)
 	|| (strpos($_SERVER['HTTP_USER_AGENT'], 'IEMobile/11') !== false && strpos($_SERVER['HTTP_USER_AGENT'], 'Touch') !== false)
	|| (strpos($_SERVER['HTTP_USER_AGENT'], 'IEMobile/10') !== false && strpos($_SERVER['HTTP_USER_AGENT'], 'Touch') !== false)
	||  strpos($_SERVER['HTTP_USER_AGENT'], 'IEMobile/9.0') !== false 
	||  strpos($_SERVER['HTTP_USER_AGENT'], 'IEMobile/8.0') !== false 
        ||  strpos($_SERVER['HTTP_USER_AGENT'], 'IEMobile/7.0') !== false 
        || (strpos($_SERVER['HTTP_USER_AGENT'], 'OPiOS') !== false && strpos($_SERVER['HTTP_USER_AGENT'], 'Mobile') !== false)
        || (strpos($_SERVER['HTTP_USER_AGENT'], 'Coast') !== false && strpos($_SERVER['HTTP_USER_AGENT'], 'Mobile') !== false) ) {
            $salt = 'mobile';
    } else {
        $salt = '';
    }
    return $salt;
}

and so is in sync with WPTouch's definitions of a mobile device.

Cheers

Keith

**Comment by KeithPantlin** [comment]
Hello Jason,

I didn't add my zc-is-mobile.php file correctly to my previous comment.

Here it is: 

function zc_is_mobile() {
    static $salt = null;
    if ( isset( $salt ) ) {
        return $salt;
    }
    if ( empty($_SERVER['HTTP_USER_AGENT']) ) {
        $salt = '';
    } elseif ( strpos($_SERVER['HTTP_USER_AGENT'], 'iPhone') !== false
        || (strpos($_SERVER['HTTP_USER_AGENT'], 'iPod') !== false && strpos($_SERVER['HTTP_USER_AGENT'], 'Mobile') !== false)
        || (strpos($_SERVER['HTTP_USER_AGENT'], 'Android') !== false && strpos($_SERVER['HTTP_USER_AGENT'], 'Mobile') !== false)
        || (strpos($_SERVER['HTTP_USER_AGENT'], 'BB') !== false && strpos($_SERVER['HTTP_USER_AGENT'], 'Mobile Safari') !== false)
        || (strpos($_SERVER['HTTP_USER_AGENT'], 'BlackBerry') !== false && strpos($_SERVER['HTTP_USER_AGENT'], 'Mobile Safari') !== false)
        || (strpos($_SERVER['HTTP_USER_AGENT'], 'Firefox') !== false && strpos($_SERVER['HTTP_USER_AGENT'], 'Mobile') !== false)
 	|| (strpos($_SERVER['HTTP_USER_AGENT'], 'IEMobile/11') !== false && strpos($_SERVER['HTTP_USER_AGENT'], 'Touch') !== false)
	|| (strpos($_SERVER['HTTP_USER_AGENT'], 'IEMobile/10') !== false && strpos($_SERVER['HTTP_USER_AGENT'], 'Touch') !== false)
	||  strpos($_SERVER['HTTP_USER_AGENT'], 'IEMobile/9.0') !== false 
	||  strpos($_SERVER['HTTP_USER_AGENT'], 'IEMobile/8.0') !== false 
        ||  strpos($_SERVER['HTTP_USER_AGENT'], 'IEMobile/7.0') !== false 
        || (strpos($_SERVER['HTTP_USER_AGENT'], 'OPiOS') !== false && strpos($_SERVER['HTTP_USER_AGENT'], 'Mobile') !== false)
        || (strpos($_SERVER['HTTP_USER_AGENT'], 'Coast') !== false && strpos($_SERVER['HTTP_USER_AGENT'], 'Mobile') !== false) ) {
            $salt = 'mobile';
    } else {
        $salt = '';
    }
    return $salt;
}
 
Cheers

Keith

**Comment by raamdev** [comment]
@KeithPantlin Thank you for the feedback and for sharing your examples above. This KB Article provides some basic advice to help site owners understand how they can detect mobile devices and it's not meant to be comprehensive. 

As of v161221, Comet Cache Pro includes a new Mobile Mode feature that helps make separating the cache for mobile devices a bit easier. See the screenshots [here](https://cometcache.com/blog/comet-cache-v161221-now-available/).

**Comment by KeithPantlin** [comment]
Hello Raam,

Thank you very much - that is most helpful.

My problem is that my web host is still using PHP 5.5.

I will definitely use the Mobile Mode when my host upgrades to PHP 5.6.

Thanks

Keith
